"""Pure decisions about what a published repo contains. No disk access."""

from __future__ import annotations

ENGINES: dict[str, str] = {"godot": "Godot", "babylon": "Babylon.js"}

_RUNTIME_ASSET_DIR = {"godot": "assets", "babylon": "src/assets"}

_ENGINE_IGNORES = {
    "godot": ["assets", "screenshots", ".godot", "*.import", "bin/", "obj/"],
    "babylon": ["/node_modules", "/dist", "/screenshots"],
}

# Written into the published repo; the agent's own knowledge base lives here.
GAME_DB_NAME = "game.db"
CRAFT_DB_NAME = "craft.db"


class UnknownEngine(Exception):
    """Raised when an engine outside ENGINES is requested."""


def _check(engine: str) -> None:
    if engine not in ENGINES:
        raise UnknownEngine(
            f"unknown engine: {engine!r} (expected one of {sorted(ENGINES)})"
        )


def runtime_asset_dir(engine: str) -> str:
    """Where the running game loads generated assets from."""
    _check(engine)
    return _RUNTIME_ASSET_DIR[engine]


def manifest_tokens(engine: str) -> dict[str, str]:
    """Tokens substituted into prompts/runtime.md when rendering CLAUDE.md."""
    _check(engine)
    return {
        "ENGINE_NAME": ENGINES[engine],
        "ENGINE_GUIDE_FILE": f"{engine}.md",
        "ASSET_SKILL_COMMAND": "/asset-gen",
    }


def skill_tokens(engine: str) -> dict[str, str]:
    """Tokens substituted into the skill tree under .claude/skills/."""
    _check(engine)
    return {
        "AGENT_NAME": "Claude",
        "ASSET_GEN_SKILL_DIR": ".claude/skills/asset-gen",
        "ASSET_SKILL_COMMAND": "/asset-gen",
        "RUNTIME_ASSET_DIR": _RUNTIME_ASSET_DIR[engine],
    }


def gitignore_lines(engine: str) -> list[str]:
    """Published instruction files are regenerated by publish.py, so ignore them."""
    _check(engine)
    return [".claude", "CLAUDE.md", f"{engine}.md", *_ENGINE_IGNORES[engine]]
