"""Pure decisions about what a published repo contains. No disk access."""

from __future__ import annotations

ENGINES: dict[str, str] = {"godot": "Godot", "babylon": "Babylon.js"}

# Where each host agent expects to find its instructions and skills, and how a
# user types a skill name at it.
AGENTS: dict[str, dict[str, str]] = {
    "claude": {
        "name": "Claude",
        "manifest": "CLAUDE.md",
        "skills_dir": ".claude/skills",
        "command_prefix": "/",
    },
    "codex": {
        "name": "Codex",
        "manifest": "AGENTS.md",
        "skills_dir": ".agents/skills",
        "command_prefix": "$",
    },
}

_RUNTIME_ASSET_DIR = {"godot": "assets", "babylon": "src/assets"}

_ENGINE_IGNORES = {
    "godot": ["assets", "screenshots", ".godot", "*.import", "bin/", "obj/"],
    "babylon": ["/node_modules", "/dist", "/screenshots"],
}

# Written into the published repo; the agent's own knowledge base lives here.
GAME_DB_NAME = "game.db"
CRAFT_DB_NAME = "craft.db"


class UnknownEngine(Exception):
    """Raised when an engine outside ENGINES is requested."""


class UnknownAgent(Exception):
    """Raised when a host agent outside AGENTS is requested."""


def _check(engine: str) -> None:
    if engine not in ENGINES:
        raise UnknownEngine(
            f"unknown engine: {engine!r} (expected one of {sorted(ENGINES)})"
        )


def _check_agent(agent: str) -> None:
    if agent not in AGENTS:
        raise UnknownAgent(
            f"unknown agent: {agent!r} (expected one of {sorted(AGENTS)})"
        )


def runtime_asset_dir(engine: str) -> str:
    """Where the running game loads generated assets from."""
    _check(engine)
    return _RUNTIME_ASSET_DIR[engine]


# Skill names, written the way each host agent expects them typed. Kept in one
# place so a new one cannot reach the manifest while missing from the skills,
# or vice versa -- an unsubstituted ${TOKEN} ships silently.
_SKILL_COMMANDS = {
    "ASSET_SKILL_COMMAND": "asset-gen",
    "KG_HARVEST_COMMAND": "kg-harvest",
    "GAME_DESIGN_COMMAND": "game-design",
}


def _commands(agent: str) -> dict[str, str]:
    prefix = AGENTS[agent]["command_prefix"]
    return {key: f"{prefix}{name}" for key, name in _SKILL_COMMANDS.items()}


def manifest_file(agent: str) -> str:
    _check_agent(agent)
    return AGENTS[agent]["manifest"]


def skills_dir(agent: str) -> str:
    _check_agent(agent)
    return AGENTS[agent]["skills_dir"]


def manifest_tokens(engine: str, agent: str = "claude") -> dict[str, str]:
    """Tokens substituted into prompts/runtime.md when rendering the manifest."""
    _check(engine)
    _check_agent(agent)
    return {
        **_commands(agent),
        "ENGINE_NAME": ENGINES[engine],
        "ENGINE_GUIDE_FILE": f"{engine}.md",
    }


def skill_tokens(
    engine: str, agent: str = "claude", godogen_root: str = ""
) -> dict[str, str]:
    """Tokens substituted into the installed skill tree."""
    _check(engine)
    _check_agent(agent)
    return {
        **_commands(agent),
        "AGENT_NAME": AGENTS[agent]["name"],
        "ASSET_GEN_SKILL_DIR": f"{AGENTS[agent]['skills_dir']}/asset-gen",
        "GODOGEN_ROOT": godogen_root,
        "RUNTIME_ASSET_DIR": _RUNTIME_ASSET_DIR[engine],
    }


_AGENT_IGNORES = {
    "claude": [".claude", ".mcp.json"],
    "codex": [".agents", ".codex"],
}


def gitignore_lines(engine: str, agent: str = "claude") -> list[str]:
    """Published instruction files are regenerated by publish.py, so ignore them.

    `.kg/` holds the game's knowledge database. It is a derived cache, not a
    source of truth -- harvest_commit.py can rebuild it from git history.
    """
    _check(engine)
    _check_agent(agent)
    return [
        *_AGENT_IGNORES[agent],
        AGENTS[agent]["manifest"],
        f"{engine}.md",
        ".kg/",
        *_ENGINE_IGNORES[engine],
    ]
